### ISSUE TITLE
Using with tabindex

### ISSUE THREAD

**Issue by Dagur** [joelpurra/plusastab#11]
Hi. I'm using plusastab so users can press enter to skip between inputs. This works fine until I apply tabindex to the fields (i have to do that dynamically). Tab follows the tabindex but the enter key ignores it and skips between every element. 

I tried using skipOnTab but that has the same effect.

**Comment by joelpurra** [comment]
@Dagur: `tabindex` is deliberately ignored by the underlying [EmulateTab](https://github.com/joelpurra/emulatetab) library and I recommend removing all `tabindex` attributes. You can read more about it in [SkipOnTab](https://github.com/joelpurra/skipontab)'s [SkipOnTab versus tabindex](https://github.com/joelpurra/skipontab/wiki/SkipOnTab-versus-tabindex), #6, joelpurra/emulatetab#4, joelpurra/emulatetab#7, joelpurra/emulatetab#9.

I encourage you to create a new project which emulates a *container-scoped* `tabindex` as `data-emulate-tabindex="true"` with `data-emulate-tabindex="42"` and `data-emulate-tabindex="17"` inside that container -- basing it on for example SkipOnTab would be a great start =)

**Comment by Dagur** [comment]
Thanks for the reply. I
