### ISSUE TITLE
plugin not working on label selector

### ISSUE THREAD

**Issue by eelco2k** [joelpurra/plusastab#14]
Would it be possible to use plusastab with <label> selector..

$("label").plusAsTab();

<label for="somelabel" tabindex="8">
<label for="someotherlabel" tabindex="8">

**Comment by joelpurra** [comment]
@eelco2k: yes, that works -- assuming that the `<label>` is a container for form input fields.

```html
<label>
    <input type="checkbox" /> Item 1
</label>
<label>
    <input type="checkbox" /> Item 2
</label>
```

[PlusAsTab works on any container](https://joelpurra.com/projects/plusastab/#containers), so you could use for example `$("form").plusAsTab()` or [`<form data-plus-as-tab="true">`](https://joelpurra.com/projects/plusastab/docs/example/enter-as-tab.html) for simplicity. Some elements might need `data-plus-as-tab="false"` depending on your needs.

Did this usage work out for you? Closing the issue for now; reopen if things are unclear (or buggy).
