### ISSUE TITLE
prevent tabindex="-1"

### ISSUE THREAD

**Issue by Mayco-Andrey-Ranghetti** [joelpurra/plusastab#15]
Hi.

Is it possible prevent elements with tabindex=-1?

**Comment by joelpurra** [comment]
@Mayco-Andrey-Ranghetti: yes, but it's [better to not use `tabindex` at all](https://github.com/joelpurra/skipontab/wiki/SkipOnTab-versus-tabindex) if you ask me. Have a look at the sister project [SkipOnTab](https://github.com/joelpurra/skipontab) for an easy solution =)

Hope that answers it! Closing the issue.
